# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        tool:
          - cmake
          - bazel
        compiler:
          - gcc
          - clang
        compiler_version:
          - 12
          - 15
        db_image:
          - mysql:5.7
          - mysql:8.0
          - mariadb:10.10
        exclude:
          - compiler: gcc
            compiler_version: 15
          - compiler: clang
            compiler_version: 12

    services:
      mysql:
        image: ${{ matrix.db_image }}
        env:
          MYSQL_DATABASE: mysqlclient_unittest
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Setup bazel
        if: matrix.tool == 'bazel'
        uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: "latest"

      - name: Setup cmake
        if: matrix.tool == 'cmake'
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "latest"

      - name: Setup Clang
        if: matrix.compiler == 'clang'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.compiler_version }}

      - name: Set Clang Compiler Env
        if: matrix.compiler == 'clang'
        run: |
          echo "CC=${LLVM_PATH}/bin/clang" >> $GITHUB_ENV
          echo "CXX=${LLVM_PATH}/bin/clang++" >> $GITHUB_ENV

      - name: Setup GCC
        uses: Dup4/actions-setup-gcc@v1
        if: matrix.compiler == 'gcc'
        with:
          version: ${{ matrix.compiler_version }}

      - name: Install deps
        run: |
          bash ./install_deps.sh

      - name: Build And Test Use Cmake
        if: matrix.tool == 'cmake'
        run: |
          make tests
          make unittest
          make benchmark

      - name: Build And Test Use Bazel
        if: matrix.tool == 'bazel'
        run: |
          make bazel_ut
          make bazel_bench
